# Generated by Django 3.1.6 on 2021-02-14 02:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 2, 14, 2, 8, 33, 107263, tzinfo=utc))),
                ('score', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TallyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('acronym', models.CharField(max_length=8)),
                ('weight', models.PositiveSmallIntegerField()),
                ('average', models.DecimalField(decimal_places=3, max_digits=5)),
                ('stdev', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TallyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('acronym', models.CharField(max_length=8)),
                ('categories', models.ManyToManyField(to='dartmun.TallyCategory')),
            ],
        ),
        migrations.CreateModel(
            name='TallyCategoryScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('zscore', models.DecimalField(decimal_places=3, max_digits=4)),
                ('scaled_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dartmun.tallycategory')),
                ('tallies', models.ManyToManyField(to='dartmun.Tally')),
            ],
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delegates', models.ManyToManyField(to='dartmun.Delegate')),
                ('tally_category_scores', models.ManyToManyField(to='dartmun.TallyCategoryScore')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dartmun.chair')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dartmun.chair')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('acronym', models.CharField(max_length=8)),
                ('delegations', models.ManyToManyField(to='dartmun.Delegation')),
                ('directors', models.ManyToManyField(related_name='directors', to='dartmun.Chair')),
                ('managers', models.ManyToManyField(related_name='managers', to='dartmun.Chair')),
            ],
        ),
    ]
