# Generated by Django 3.1.6 on 2021-02-21 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeTallyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('stdev', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('delegates', models.ManyToManyField(to='dartmun.Delegate')),
            ],
        ),
        migrations.CreateModel(
            name='TallyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('acronym', models.CharField(max_length=8)),
                ('weight', models.PositiveSmallIntegerField()),
                ('scaled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TallyScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('delegation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.delegation')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dartmun.chair')),
            ],
        ),
        migrations.CreateModel(
            name='TallyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('acronym', models.CharField(max_length=8)),
                ('categories', models.ManyToManyField(to='dartmun.TallyCategory')),
            ],
        ),
        migrations.CreateModel(
            name='TallyCategoryScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('zscore', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('scaled_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dartmun.committeetallycategory')),
                ('tallies', models.ManyToManyField(to='dartmun.TallyScore')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('delegation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.delegation')),
                ('tally_category_scores', models.ManyToManyField(to='dartmun.TallyCategoryScore')),
            ],
        ),
        migrations.AddField(
            model_name='committeetallycategory',
            name='tally_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dartmun.tallycategory'),
        ),
        migrations.CreateModel(
            name='CommitteeManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dartmun.chair')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dartmun.chair')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('acronym', models.CharField(max_length=8)),
                ('delegations', models.ManyToManyField(to='dartmun.Delegation')),
                ('directors', models.ManyToManyField(to='dartmun.CommitteeDirector')),
                ('managers', models.ManyToManyField(to='dartmun.CommitteeManager')),
                ('score_managers', models.ManyToManyField(to='dartmun.ScoreManager')),
                ('tallies', models.ManyToManyField(to='dartmun.TallyScore')),
                ('tally_categories', models.ManyToManyField(to='dartmun.CommitteeTallyCategory')),
            ],
        ),
    ]
