# Generated by Django 3.1.6 on 2021-02-14 02:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 2, 8, 39, 848184, tzinfo=utc)),
        ),
    ]
