# Generated by Django 3.1.6 on 2021-02-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0002_auto_20210225_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlipromanager',
            name='spoke',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
