# Generated by Django 3.1.6 on 2021-02-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0002_auto_20210214_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
