# Generated by Django 3.1.6 on 2021-02-21 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0003_auto_20210221_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeetallycategory',
            old_name='tally_category',
            new_name='category',
        ),
    ]
