# Generated by Django 3.1.6 on 2021-02-14 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0003_auto_20210214_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dartmun.chair')),
            ],
        ),
        migrations.DeleteModel(
            name='Tally',
        ),
        migrations.AlterField(
            model_name='tallycategoryscore',
            name='tallies',
            field=models.ManyToManyField(to='dartmun.TallyScore'),
        ),
    ]
