# Generated by Django 3.1.6 on 2021-02-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0003_parlipromanager_spoke'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parlipromanager',
            old_name='first',
            new_name='last',
        ),
        migrations.AddField(
            model_name='parlipromanager',
            name='caucus_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
