# Generated by Django 3.1.6 on 2021-02-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0004_auto_20210214_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallycategory',
            name='scaled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tallycategory',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tallycategory',
            name='stdev',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
