# Generated by Django 3.1.6 on 2021-02-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0005_auto_20210221_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='category_average',
            field=models.FloatField(default=87.5),
        ),
        migrations.AddField(
            model_name='committee',
            name='category_stdev',
            field=models.FloatField(default=5),
        ),
    ]
