# Generated by Django 3.1.6 on 2021-02-28 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0005_auto_20210228_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parlipromanager',
            name='caucus_duration',
        ),
        migrations.RemoveField(
            model_name='parlipromanager',
            name='caucus_until',
        ),
        migrations.RemoveField(
            model_name='parlipromanager',
            name='current_st',
        ),
        migrations.RemoveField(
            model_name='parlipromanager',
            name='last',
        ),
        migrations.RemoveField(
            model_name='parlipromanager',
            name='raised_by',
        ),
        migrations.RemoveField(
            model_name='parlipromanager',
            name='remaining_speeches',
        ),
        migrations.RemoveField(
            model_name='parlipromanager',
            name='spoke',
        ),
        migrations.CreateModel(
            name='CaucusManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caucus_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('caucus_until', models.TimeField(blank=True, null=True)),
                ('current_st', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('remaining_speeches', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last', models.BooleanField(blank=True, null=True)),
                ('spoke', models.BooleanField(blank=True, null=True)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.delegation')),
            ],
        ),
        migrations.AddField(
            model_name='parlipromanager',
            name='caucus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.caucusmanager'),
        ),
    ]
