# Generated by Django 3.1.6 on 2021-02-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0005_auto_20210214_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='directors',
            field=models.ManyToManyField(to='dartmun.CommitteeDirector'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='managers',
            field=models.ManyToManyField(to='dartmun.CommitteeManager'),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
