# Generated by Django 3.1.6 on 2021-02-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0006_auto_20210214_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyscore',
            name='time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tallycategoryscore',
            name='raw_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='tallycategoryscore',
            name='scaled_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tallycategoryscore',
            name='zscore',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
