# Generated by Django 3.1.6 on 2021-02-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0006_auto_20210221_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeetallycategory',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='committeetallycategory',
            name='stdev',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
