# Generated by Django 3.1.6 on 2021-02-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0006_auto_20210228_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chair',
            name='major',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='chair',
            name='year',
            field=models.PositiveSmallIntegerField(default=2024, null=True),
        ),
    ]
