# Generated by Django 3.1.6 on 2021-02-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0007_auto_20210214_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyscore',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
