# Generated by Django 3.1.6 on 2021-02-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0007_auto_20210228_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caucusmanager',
            name='spoke',
        ),
        migrations.AlterField(
            model_name='parlipromanager',
            name='motion_list',
            field=models.ManyToManyField(blank=True, to='dartmun.MotionEntry'),
        ),
        migrations.AlterField(
            model_name='parlipromanager',
            name='speaker_list',
            field=models.ManyToManyField(blank=True, to='dartmun.SpeechEntry'),
        ),
    ]
