# Generated by Django 3.1.6 on 2021-02-21 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0008_tallyscore_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='delegations',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='managers',
        ),
        migrations.CreateModel(
            name='PeopleManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegations', models.ManyToManyField(to='dartmun.Delegation')),
                ('directors', models.ManyToManyField(to='dartmun.CommitteeDirector')),
                ('managers', models.ManyToManyField(to='dartmun.CommitteeManager')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.peoplemanager'),
        ),
    ]
