# Generated by Django 3.1.6 on 2021-02-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0008_auto_20210228_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='caucusmanager',
            name='spoke',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
