# Generated by Django 3.1.6 on 2021-02-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0008_tallyscore_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallycategoryscore',
            name='raw_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
