# Generated by Django 3.1.6 on 2021-02-21 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0009_auto_20210221_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='category_average',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='category_stdev',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='score_managers',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='tally_categories',
        ),
        migrations.CreateModel(
            name='GradesManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_average', models.FloatField(default=87.5)),
                ('category_stdev', models.FloatField(default=5)),
                ('score_managers', models.ManyToManyField(to='dartmun.ScoreManager')),
                ('tally_categories', models.ManyToManyField(to='dartmun.CommitteeTallyCategory')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='grades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.gradesmanager'),
        ),
    ]
