# Generated by Django 3.1.6 on 2021-02-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0010_auto_20210221_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='tallies',
        ),
        migrations.AddField(
            model_name='gradesmanager',
            name='tallies',
            field=models.ManyToManyField(to='dartmun.TallyScore'),
        ),
    ]
