# Generated by Django 3.1.6 on 2021-03-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0010_auto_20210302_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterionscore',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
