# Generated by Django 3.1.6 on 2021-02-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0011_auto_20210221_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesmanager',
            name='need_update',
            field=models.BooleanField(default=False),
        ),
    ]
