# Generated by Django 3.1.6 on 2021-03-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0012_auto_20210302_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallyscore',
            name='score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tallyscore',
            name='scorer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.chair'),
        ),
    ]
