# Generated by Django 3.1.6 on 2021-02-21 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0012_gradesmanager_need_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=64)),
                ('acronym', models.CharField(max_length=8)),
                ('speeches', models.BooleanField(default=False)),
                ('yielding', models.BooleanField(default=False)),
                ('duration', models.BooleanField(default=False)),
                ('speaking_time', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion', models.CharField(max_length=64)),
                ('vote_simple', models.BooleanField(default=True)),
                ('speeches', models.BooleanField(default=False)),
                ('duration', models.BooleanField(default=False)),
                ('speaking_time', models.BooleanField(default=False)),
                ('topic', models.BooleanField(default=False)),
                ('purpose', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MotionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.FloatField(default=0)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dartmun.delegation')),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dartmun.motion')),
            ],
        ),
        migrations.AlterField(
            model_name='committee',
            name='grades',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.gradesmanager'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='people',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.peoplemanager'),
        ),
        migrations.CreateModel(
            name='SpeechEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dartmun.delegation')),
            ],
        ),
        migrations.CreateModel(
            name='ParliProManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dartmun.debatemode')),
                ('motion_list', models.ManyToManyField(to='dartmun.MotionEntry')),
                ('speaker_list', models.ManyToManyField(to='dartmun.SpeechEntry')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='parli_pro',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.parlipromanager'),
        ),
    ]
