# Generated by Django 3.1.6 on 2021-02-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0014_auto_20210221_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlipromanager',
            name='caucus_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parlipromanager',
            name='current_st',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='parlipromanager',
            name='default_st',
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='peoplemanager',
            name='simple_majority',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peoplemanager',
            name='super_majority',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
