# Generated by Django 3.1.6 on 2021-03-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0014_auto_20210302_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallycategoryscore',
            name='tallies',
            field=models.ManyToManyField(blank=True, to='dartmun.TallyScore'),
        ),
    ]
