# Generated by Django 3.1.6 on 2021-03-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0015_auto_20210304_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplemanager',
            name='min_signatory',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peoplemanager',
            name='quorum',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
