# Generated by Django 3.1.6 on 2021-02-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0017_auto_20210221_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='delegation',
            name='voting',
            field=models.BooleanField(default=False),
        ),
    ]
