# Generated by Django 3.1.6 on 2021-03-06 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0017_auto_20210305_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingmanager',
            name='resolutions',
            field=models.ManyToManyField(related_name='committee_resos', to='dartmun.Resolution'),
        ),
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_type', models.CharField(choices=[('A', 'Add'), ('M', 'Modify'), ('S', 'Strike')], max_length=16)),
                ('clause', models.PositiveSmallIntegerField()),
                ('subclause', models.CharField(max_length=2)),
                ('subsubclause', models.CharField(max_length=5)),
                ('friendly', models.BooleanField(default=False)),
                ('score', models.PositiveSmallIntegerField()),
                ('old', models.TextField(blank=True, null=True)),
                ('new', models.TextField(blank=True, null=True)),
                ('passed', models.BooleanField(null=True)),
                ('signatories', models.ManyToManyField(related_name='amend_signatories', to='dartmun.Delegation')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amend_sponsor', to='dartmun.delegation')),
            ],
        ),
        migrations.AddField(
            model_name='resolution',
            name='amendments',
            field=models.ManyToManyField(to='dartmun.Amendment'),
        ),
        migrations.AddField(
            model_name='writingmanager',
            name='current_amend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_amend', to='dartmun.amendment'),
        ),
    ]
