# Generated by Django 3.1.6 on 2021-02-22 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0018_auto_20210221_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechentry',
            name='delegation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dartmun.delegation'),
        ),
    ]
