# Generated by Django 3.1.6 on 2021-03-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0018_auto_20210306_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolution',
            name='rubric_entry',
        ),
        migrations.RemoveField(
            model_name='resolution',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='workingpaper',
            name='topic',
        ),
        migrations.AddField(
            model_name='topic',
            name='resolutions',
            field=models.ManyToManyField(to='dartmun.Resolution'),
        ),
        migrations.AddField(
            model_name='topic',
            name='working_papers',
            field=models.ManyToManyField(to='dartmun.WorkingPaper'),
        ),
    ]
