# Generated by Django 3.1.6 on 2021-02-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0019_auto_20210222_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionentry',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motionentry',
            name='purpose',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='motionentry',
            name='speaking_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motionentry',
            name='topic',
            field=models.BooleanField(default=False),
        ),
    ]
