# Generated by Django 3.1.6 on 2021-03-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0020_auto_20210307_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolution',
            name='signatories',
        ),
        migrations.RemoveField(
            model_name='resolution',
            name='sponsors',
        ),
        migrations.RemoveField(
            model_name='workingpaper',
            name='signatories',
        ),
        migrations.RemoveField(
            model_name='workingpaper',
            name='sponsors',
        ),
        migrations.CreateModel(
            name='SponSigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signatories', models.ManyToManyField(related_name='signatories', to='dartmun.Delegation')),
                ('sponsors', models.ManyToManyField(related_name='sponsors', to='dartmun.Delegation')),
            ],
        ),
        migrations.AddField(
            model_name='resolution',
            name='sponsigs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.sponsigs'),
        ),
        migrations.AddField(
            model_name='workingpaper',
            name='sponsigs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.sponsigs'),
        ),
    ]
