# Generated by Django 3.1.6 on 2021-02-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0020_auto_20210223_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128)),
                ('number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='parlipromanager',
            name='remaining_speeches',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
