# Generated by Django 3.1.6 on 2021-02-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0021_auto_20210223_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlipromanager',
            name='current_st',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
