# Generated by Django 3.1.6 on 2021-03-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0021_auto_20210309_2055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SponSigs',
            new_name='SponSig',
        ),
        migrations.RenameField(
            model_name='resolution',
            old_name='sponsigs',
            new_name='SponSig',
        ),
        migrations.RenameField(
            model_name='workingpaper',
            old_name='sponsigs',
            new_name='sponsig',
        ),
    ]
