# Generated by Django 3.1.6 on 2021-03-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0022_auto_20210309_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resolution',
            old_name='SponSig',
            new_name='sponsig',
        ),
    ]
