# Generated by Django 3.1.6 on 2021-02-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0022_auto_20210223_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='topics',
            field=models.ManyToManyField(to='dartmun.Topic'),
        ),
    ]
