# Generated by Django 3.1.6 on 2021-02-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0023_committee_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlipromanager',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
