# Generated by Django 3.1.6 on 2021-02-23 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0024_parlipromanager_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlipromanager',
            name='current_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.topic'),
        ),
    ]
