# Generated by Django 3.1.6 on 2021-03-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0024_auto_20210313_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendment',
            name='votes_abstain',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='amendment',
            name='votes_against',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='amendment',
            name='votes_for',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='committeetallycategory',
            name='points_possible',
            field=models.FloatField(default=0),
        ),
    ]
