# Generated by Django 3.1.6 on 2021-03-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0025_auto_20210314_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amendment',
            name='subclause',
        ),
        migrations.RemoveField(
            model_name='amendment',
            name='subsubclause',
        ),
        migrations.AlterField(
            model_name='amendment',
            name='clause',
            field=models.CharField(max_length=16),
        ),
    ]
