# Generated by Django 3.1.6 on 2021-03-17 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0026_auto_20210316_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallycategoryscore',
            name='delegation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.delegation'),
        ),
    ]
