# Generated by Django 3.1.6 on 2021-02-24 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0026_auto_20210223_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(max_length=64)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dartmun.criterion')),
            ],
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.TextField()),
                ('points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('max_possible', models.FloatField()),
                ('criteria', models.ManyToManyField(to='dartmun.Criterion')),
                ('tally_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dartmun.tallycategory')),
            ],
        ),
        migrations.CreateModel(
            name='RubricEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('criterion_scores', models.ManyToManyField(to='dartmun.CriterionScore')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dartmun.rubric')),
            ],
        ),
        migrations.AddField(
            model_name='criterionscore',
            name='descriptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.descriptor'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='possible_scores',
            field=models.ManyToManyField(to='dartmun.Descriptor'),
        ),
    ]
