# Generated by Django 3.1.6 on 2021-03-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0027_tallycategoryscore_delegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplemanager',
            name='double_delegation',
            field=models.BooleanField(default=False),
        ),
    ]
