# Generated by Django 3.1.6 on 2021-02-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0027_auto_20210224_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplemanager',
            name='number_present',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
