# Generated by Django 3.1.6 on 2021-02-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0028_peoplemanager_number_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='present',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='voting',
            field=models.BooleanField(null=True),
        ),
    ]
