# Generated by Django 3.1.6 on 2021-03-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0028_peoplemanager_double_delegation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplemanager',
            name='managers',
            field=models.ManyToManyField(blank=True, to='dartmun.CommitteeManager'),
        ),
    ]
