# Generated by Django 3.1.6 on 2021-03-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0029_auto_20210321_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeetallycategory',
            name='average',
        ),
        migrations.AddField(
            model_name='committeetallycategory',
            name='raw_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
