# Generated by Django 3.1.6 on 2021-03-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0031_auto_20210321_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeetallycategory',
            name='scaled_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
