# Generated by Django 3.1.6 on 2021-03-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0032_committeetallycategory_scaled_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesmanager',
            name='committee_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
