# Generated by Django 3.1.6 on 2021-03-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0037_auto_20210328_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='committees',
            field=models.ManyToManyField(to='dartmun.Committee'),
        ),
    ]
