# Generated by Django 3.1.6 on 2021-03-30 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0038_organ_committees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amendment',
            name='signatories',
        ),
        migrations.RemoveField(
            model_name='amendment',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='amendment',
            name='sponsig',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.sponsig'),
        ),
    ]
