# Generated by Django 3.1.6 on 2021-03-30 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0040_amendment_introduced'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='current_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.session'),
        ),
    ]
