# Generated by Django 3.1.6 on 2021-03-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0041_committee_current_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dartmun.session')),
            ],
        ),
        migrations.AddField(
            model_name='delegation',
            name='attendance_records',
            field=models.ManyToManyField(to='dartmun.AttendanceRecord'),
        ),
    ]
