# Generated by Django 3.1.6 on 2021-03-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0042_auto_20210330_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='adjourned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BD', to='dartmun.delegation')),
                ('honorable_mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HM', to='dartmun.delegation')),
                ('outstanding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OD', to='dartmun.delegation')),
            ],
        ),
        migrations.AddField(
            model_name='gradesmanager',
            name='awards',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dartmun.awards'),
        ),
    ]
