# Generated by Django 3.1.6 on 2021-03-30 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0043_auto_20210331_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='best_delegate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BD', to='dartmun.delegation'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='honorable_mention',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HM', to='dartmun.delegation'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='outstanding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OD', to='dartmun.delegation'),
        ),
    ]
