# Generated by Django 3.1.6 on 2021-03-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dartmun', '0044_auto_20210331_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awards',
            old_name='outstanding',
            new_name='outstanding_delegate',
        ),
    ]
